[2022-12-05T11:02:49.342+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.old_a scheduled__2022-12-05T00:05:00+00:00 [queued]>
[2022-12-05T11:02:49.358+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.old_a scheduled__2022-12-05T00:05:00+00:00 [queued]>
[2022-12-05T11:02:49.359+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T11:02:49.359+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-05T11:02:49.359+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T11:02:49.456+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): old_a> on 2022-12-05 00:05:00+00:00
[2022-12-05T11:02:49.468+0000] {standard_task_runner.py:55} INFO - Started process 182 to run task
[2022-12-05T11:02:49.474+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Practice_Airflow', 'old_a', 'scheduled__2022-12-05T00:05:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_pr.py', '--cfg-path', '/tmp/tmp3ogypfs7']
[2022-12-05T11:02:49.478+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask old_a
[2022-12-05T11:02:49.606+0000] {task_command.py:376} INFO - Running <TaskInstance: Practice_Airflow.old_a scheduled__2022-12-05T00:05:00+00:00 [running]> on host a5be4f489b88
[2022-12-05T11:02:49.841+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Practice_Airflow
AIRFLOW_CTX_TASK_ID=old_a
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T00:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-05T00:05:00+00:00
[2022-12-05T11:02:50.035+0000] {logging_mixin.py:137} INFO - Data from hw_200.csv file:
     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]
[2022-12-05T11:02:50.038+0000] {logging_mixin.py:137} INFO - Кол-во строк в df: 200
[2022-12-05T11:02:50.256+0000] {crypto.py:84} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-12-05T11:02:50.260+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "variable_key_uq"
DETAIL:  Key (key)=(csv_path) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Airflow_pr.py", line 28, in csv_procedure
    Variable.set(key = "csv_path", value = "/opt/airflow/dags/hw_200.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 180, in set
    session.flush()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3485, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3445, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 249, in save_obj
    insert,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1224, in _emit_insert_statements
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "variable_key_uq"
DETAIL:  Key (key)=(csv_path) already exists.

[SQL: INSERT INTO variable (key, val, description, is_encrypted) VALUES (%(key)s, %(val)s, %(description)s, %(is_encrypted)s) RETURNING variable.id]
[parameters: {'key': 'csv_path', 'val': '/opt/airflow/dags/hw_200.csv', 'description': None, 'is_encrypted': False}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2022-12-05T11:02:50.792+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Practice_Airflow, task_id=old_a, execution_date=20221205T000500, start_date=20221205T110249, end_date=20221205T110250
[2022-12-05T11:02:51.051+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 138 for task old_a ((psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "variable_key_uq"
DETAIL:  Key (key)=(csv_path) already exists.

[SQL: INSERT INTO variable (key, val, description, is_encrypted) VALUES (%(key)s, %(val)s, %(description)s, %(is_encrypted)s) RETURNING variable.id]
[parameters: {'key': 'csv_path', 'val': '/opt/airflow/dags/hw_200.csv', 'description': None, 'is_encrypted': False}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 182)
[2022-12-05T11:02:51.070+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-05T11:02:51.121+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
