[2022-12-01T13:50:35.205+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.read_csv_file manual__2022-12-01T13:50:28.253253+00:00 [queued]>
[2022-12-01T13:50:35.213+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.read_csv_file manual__2022-12-01T13:50:28.253253+00:00 [queued]>
[2022-12-01T13:50:35.213+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T13:50:35.213+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-01T13:50:35.214+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T13:50:35.397+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv_file> on 2022-12-01 13:50:28.253253+00:00
[2022-12-01T13:50:35.401+0000] {standard_task_runner.py:55} INFO - Started process 2069 to run task
[2022-12-01T13:50:35.404+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Practice_Airflow', 'read_csv_file', 'manual__2022-12-01T13:50:28.253253+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_pr.py', '--cfg-path', '/tmp/tmpkgasjhjr']
[2022-12-01T13:50:35.405+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask read_csv_file
[2022-12-01T13:50:35.506+0000] {task_command.py:376} INFO - Running <TaskInstance: Practice_Airflow.read_csv_file manual__2022-12-01T13:50:28.253253+00:00 [running]> on host a5be4f489b88
[2022-12-01T13:50:35.638+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Practice_Airflow
AIRFLOW_CTX_TASK_ID=read_csv_file
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T13:50:28.253253+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-01T13:50:28.253253+00:00
[2022-12-01T13:50:35.640+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Airflow_pr.py", line 10, in read_csv
    df = pd.read_csv('./dags:/opt/airflow/dags/hw_200.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './dags:/opt/airflow/dags/hw_200.csv'
[2022-12-01T13:50:35.668+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Practice_Airflow, task_id=read_csv_file, execution_date=20221201T135028, start_date=20221201T135035, end_date=20221201T135035
[2022-12-01T13:50:35.719+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task read_csv_file ([Errno 2] No such file or directory: './dags:/opt/airflow/dags/hw_200.csv'; 2069)
[2022-12-01T13:50:35.736+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-01T13:50:35.749+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
