[2022-12-05T11:19:47.622+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.old_a manual__2022-12-05T11:19:44.082708+00:00 [queued]>
[2022-12-05T11:19:47.630+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Practice_Airflow.old_a manual__2022-12-05T11:19:44.082708+00:00 [queued]>
[2022-12-05T11:19:47.631+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T11:19:47.631+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-05T11:19:47.631+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T11:19:47.707+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): old_a> on 2022-12-05 11:19:44.082708+00:00
[2022-12-05T11:19:47.711+0000] {standard_task_runner.py:55} INFO - Started process 1914 to run task
[2022-12-05T11:19:47.713+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Practice_Airflow', 'old_a', 'manual__2022-12-05T11:19:44.082708+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_pr.py', '--cfg-path', '/tmp/tmpxjtbmnbe']
[2022-12-05T11:19:47.714+0000] {standard_task_runner.py:83} INFO - Job 428: Subtask old_a
[2022-12-05T11:19:47.787+0000] {task_command.py:376} INFO - Running <TaskInstance: Practice_Airflow.old_a manual__2022-12-05T11:19:44.082708+00:00 [running]> on host a5be4f489b88
[2022-12-05T11:19:47.929+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Practice_Airflow
AIRFLOW_CTX_TASK_ID=old_a
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T11:19:44.082708+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-05T11:19:44.082708+00:00
[2022-12-05T11:19:47.940+0000] {logging_mixin.py:137} INFO - Data from hw_200.csv file:
     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]
[2022-12-05T11:19:47.941+0000] {logging_mixin.py:137} INFO - Кол-во строк в df: 200
[2022-12-05T11:19:47.979+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Airflow_pr.py", line 28, in csv_procedure
    if Variable.get("csv_path", deserialize_json=False) == KeyError:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_path does not exist'
[2022-12-05T11:19:47.989+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Practice_Airflow, task_id=old_a, execution_date=20221205T111944, start_date=20221205T111947, end_date=20221205T111947
[2022-12-05T11:19:48.029+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 428 for task old_a ('Variable csv_path does not exist'; 1914)
[2022-12-05T11:19:48.045+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-05T11:19:48.066+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
